name: CI

on:
    push:
        branches:
            - main
            - master
    pull_request: {}

concurrency:
    group: ci-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: 'Tests'
        runs-on: ubuntu-latest

        steps:
       - uses: actions/checkout@v2
            - uses: actions/checkout@v2
            - uses: volta-cli/action@v1
              with:
                  node-version: 16.x
                  yarn-version: 1.x
            - name: Install Dependencies
              run: yarn install --frozen-lockfile --non-interactive


        floating:
        name: 'Floating Dependencies'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: volta-cli/action@v1
              with:
                  node-version: 16.x
                  yarn-version: 1.x
            - name: Install Dependencies
              run: yarn install --no-lockfile  --non-interactive


    try-scenarios:
        name: ${{ matrix.ember-try-scenario }}
        runs-on: ubuntu-latest
        needs: 'test'
        strategy:
            fail-fast: false
            matrix:
                ember-try-scenario:
                    - ember-lts-3.28
                    - ember-lts-4.0
                    - ember-release
                    - ember-beta
                    - ember-canary
                    - ember-classic
                    - embroider-safe
                    - embroider-optimized

        steps:
            - uses: actions/checkout@v2
            - uses: volta-cli/action@v1
              with:
                  node-version: 16.x
                  yarn-version: 1.x
            - name: Install Dependencies
              run: yarn install --frozen-lockfile --non-interactive
            - name: Test
              env:
                  EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}

